---
name: "CI/CD"

"on":
  push: {}

jobs:
  pre-commit:
    runs-on: "ubuntu-24.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v6.0.2"
      - name: "Cache mise tools"
        uses: "actions/cache@v5.0.5"
        with:
          path: "${{ github.workspace }}/.cache/mise"
          key: "${{ hashFiles('mise.toml') }}"
      - name: "Setup mise"
        uses: "jdx/mise-action@v4.0.1"
      - name: "Run linting, building, tests"
        run: "mise run pre-commit"

  determine-version-job:
    runs-on: "ubuntu-24.04"
    outputs:
      version: "${{ steps.get_version.outputs.version }}"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v6.0.2"
        with:
          fetch-depth: 0
      - name: "Cache mise tools"
        uses: "actions/cache@v5.0.5"
        with:
          path: "${{ github.workspace }}/.cache/mise"
          key: "${{ hashFiles('mise.toml') }}"
      - name: "Setup mise"
        uses: "jdx/mise-action@v4.0.1"
      - name: "Run verscout next"
        id: "get_version"
        run: |
          VERSION=$(mise run verscout)
          if [ -z "$VERSION" ]; then
            exit 0
          fi
          if [ "${{ github.ref_name }}" != "${{ github.event.repository.default_branch }}" ]; then
            VERSION="${VERSION}-rc"
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  release-job:
    runs-on: "ubuntu-24.04"
    needs:
      - "determine-version-job"
    if: "needs.determine-version-job.outputs.VERSION != ''"
    permissions:
      contents: "write"
      packages: "write"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v6.0.2"
        with:
          fetch-depth: 0
      - name: "Cache mise tools"
        uses: "actions/cache@v5.0.5"
        with:
          path: "${{ github.workspace }}/.cache/mise"
          key: "${{ hashFiles('mise.toml') }}"
      - name: "Setup mise"
        uses: "jdx/mise-action@v4.0.1"
      - name: "Prepare release artifacts"
        run: "mise run release:prepare --version ${{ needs.determine-version-job.outputs.version }}"
      - name: "Login to helm registry"
        run: "helm registry login ghcr.io --username ernail --password ${{ secrets.GITHUB_TOKEN }}"
      - name: "Publish Helm Chart"
        run: "helm push hedgedoc-${{ needs.determine-version-job.outputs.version }}.tgz oci://ghcr.io/ernail/charts"
      - name: "Create GitHub Release"
        uses: "softprops/action-gh-release@v2.4.2"
        with:
          tag_name: "${{ needs.determine-version-job.outputs.VERSION }}"
          body_path: "release-notes.md"
          files: "hedgedoc-${{ needs.determine-version-job.outputs.version }}.tgz"
          draft: true
